import Navbar from "@components/navbar/navbar"
import "@styles/global.css"

export const metadata = {
  title: 'Thoriq Akbar Virgiawan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
